# Form implementation generated from reading ui file 'home_widget_qt.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import (QWidget)

class Ui_Form(QWidget):
    def __init__(self, parent, ):
        super(Ui_Form, self).__init__(parent)

        #self.from_widget = form_widget
        self.setObjectName("Form")
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_4 = QtWidgets.QScrollArea(self)
        self.scrollArea_4.setLineWidth(0)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 675, 125))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.sing_up = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        self.sing_up.setObjectName("sing_up")
        self.horizontalLayout_3.addWidget(self.sing_up)
        self.sing_in = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        self.sing_in.setObjectName("sing_in")
        self.horizontalLayout_3.addWidget(self.sing_in)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_3.addWidget(self.scrollArea_4)
        self.line_2 = QtWidgets.QFrame(self)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.scrollArea_5 = QtWidgets.QScrollArea(self)
        self.scrollArea_5.setLineWidth(0)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 675, 125))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(245, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.auto_start = QtWidgets.QPushButton(self.scrollAreaWidgetContents_7)
        self.auto_start.setMinimumSize(QtCore.QSize(122, 24))
        self.auto_start.setMaximumSize(QtCore.QSize(122, 24))
        self.auto_start.setObjectName("auto_start")
        self.horizontalLayout_4.addWidget(self.auto_start)
        spacerItem1 = QtWidgets.QSpacerItem(260, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_7)
        self.verticalLayout_3.addWidget(self.scrollArea_5)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.scrollArea_6 = QtWidgets.QScrollArea(self)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 677, 268))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea_6)

        self.retranslateUi()
        self.addActionBattons()
        QtCore.QMetaObject.connectSlotsByName(self)
        

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Używasz aplikacji w trybie gość, zaloguj się albo zarejestruj!"))
        self.sing_up.setText(_translate("Form", "Zarejestruj się"))
        self.sing_in.setText(_translate("Form", "Zaloguj się "))
        self.auto_start.setText(_translate("Form", "Rozpocznij tryb AUTO"))
    
    def addActionBattons(self):
        self.sing_up.clicked.connect(lambda:self.show_screen())
        self.sing_in.clicked.connect(lambda:self.show_screen())
        self.auto_start.clicked.connect(lambda:self.show_screen())

    def show_screen(self):
        self.parent().sing_in_show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
