# Form implementation generated from reading ui file 'sing_in_widget_qt.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import (QWidget)



class SingIn(QWidget):
    def __init__(self, parent):
        super(SingIn, self).__init__(parent)

    
        self.setObjectName("Form")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(230, 130, 49, 16))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextEdit(self)
        
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))



