# Form implementation generated from reading ui file '.\sing_in_widget.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import (QWidget)



class SingIn(QWidget):
    def __init__(self, parent, form_widget):
        super(SingIn, self).__init__(parent)

        self.from_widget = form_widget
        
        self.from_widget.setObjectName("Form")
        self.from_widget.resize(400, 300)
        QtCore.QMetaObject.connectSlotsByName(self.from_widget)


