# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExampleProto.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExampleProto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x45xampleProto.proto\"\x14\n\x03LED\x12\r\n\x05state\x18\x01 \x01(\x08\"i\n\nDataPacket\x12\x0e\n\x06valueA\x18\x01 \x01(\x01\x12\x0e\n\x06valueB\x18\x02 \x01(\x01\x12\x0e\n\x06valueC\x18\x03 \x01(\x01\x12\x15\n\rconstantValue\x18\x04 \x01(\x01\x12\x14\n\x0cpacketNumber\x18\x05 \x01(\r\"\x97\x01\n\rDeviceRequest\x12(\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1a.DeviceRequest.RequestType\x12\x16\n\x08ledState\x18\x02 \x01(\x0b\x32\x04.LED\"D\n\x0bRequestType\x12\n\n\x06UNUSED\x10\x00\x12\x14\n\x10\x43HANGE_LED_STATE\x10\x01\x12\t\n\x05START\x10\x02\x12\x08\n\x04STOP\x10\x03\"\x82\x01\n\x0e\x44\x65viceResponse\x12*\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1c.DeviceResponse.ResponseType\"D\n\x0cResponseType\x12\n\n\x06UNUSED\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x0c\n\x08\x42\x41\x44_TYPE\x10\x02\x12\x12\n\x0ePROTOBUF_ERROR\x10\x03\x62\x06proto3'
)



_DEVICEREQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='DeviceRequest.RequestType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNUSED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHANGE_LED_STATE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='START', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=235,
  serialized_end=303,
)
_sym_db.RegisterEnumDescriptor(_DEVICEREQUEST_REQUESTTYPE)

_DEVICERESPONSE_RESPONSETYPE = _descriptor.EnumDescriptor(
  name='ResponseType',
  full_name='DeviceResponse.ResponseType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNUSED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAD_TYPE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROTOBUF_ERROR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=368,
  serialized_end=436,
)
_sym_db.RegisterEnumDescriptor(_DEVICERESPONSE_RESPONSETYPE)


_LED = _descriptor.Descriptor(
  name='LED',
  full_name='LED',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='LED.state', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=42,
)


_DATAPACKET = _descriptor.Descriptor(
  name='DataPacket',
  full_name='DataPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valueA', full_name='DataPacket.valueA', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valueB', full_name='DataPacket.valueB', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valueC', full_name='DataPacket.valueC', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='constantValue', full_name='DataPacket.constantValue', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='packetNumber', full_name='DataPacket.packetNumber', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=149,
)


_DEVICEREQUEST = _descriptor.Descriptor(
  name='DeviceRequest',
  full_name='DeviceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='DeviceRequest.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ledState', full_name='DeviceRequest.ledState', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DEVICEREQUEST_REQUESTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=303,
)


_DEVICERESPONSE = _descriptor.Descriptor(
  name='DeviceResponse',
  full_name='DeviceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='DeviceResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DEVICERESPONSE_RESPONSETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=436,
)

_DEVICEREQUEST.fields_by_name['code'].enum_type = _DEVICEREQUEST_REQUESTTYPE
_DEVICEREQUEST.fields_by_name['ledState'].message_type = _LED
_DEVICEREQUEST_REQUESTTYPE.containing_type = _DEVICEREQUEST
_DEVICERESPONSE.fields_by_name['code'].enum_type = _DEVICERESPONSE_RESPONSETYPE
_DEVICERESPONSE_RESPONSETYPE.containing_type = _DEVICERESPONSE
DESCRIPTOR.message_types_by_name['LED'] = _LED
DESCRIPTOR.message_types_by_name['DataPacket'] = _DATAPACKET
DESCRIPTOR.message_types_by_name['DeviceRequest'] = _DEVICEREQUEST
DESCRIPTOR.message_types_by_name['DeviceResponse'] = _DEVICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LED = _reflection.GeneratedProtocolMessageType('LED', (_message.Message,), {
  'DESCRIPTOR' : _LED,
  '__module__' : 'ExampleProto_pb2'
  # @@protoc_insertion_point(class_scope:LED)
  })
_sym_db.RegisterMessage(LED)

DataPacket = _reflection.GeneratedProtocolMessageType('DataPacket', (_message.Message,), {
  'DESCRIPTOR' : _DATAPACKET,
  '__module__' : 'ExampleProto_pb2'
  # @@protoc_insertion_point(class_scope:DataPacket)
  })
_sym_db.RegisterMessage(DataPacket)

DeviceRequest = _reflection.GeneratedProtocolMessageType('DeviceRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEREQUEST,
  '__module__' : 'ExampleProto_pb2'
  # @@protoc_insertion_point(class_scope:DeviceRequest)
  })
_sym_db.RegisterMessage(DeviceRequest)

DeviceResponse = _reflection.GeneratedProtocolMessageType('DeviceResponse', (_message.Message,), {
  'DESCRIPTOR' : _DEVICERESPONSE,
  '__module__' : 'ExampleProto_pb2'
  # @@protoc_insertion_point(class_scope:DeviceResponse)
  })
_sym_db.RegisterMessage(DeviceResponse)


# @@protoc_insertion_point(module_scope)
