# Form implementation generated from reading ui file 'choose_method_widget.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIntValidator 
from PyQt6.QtWidgets import (QWidget,QMessageBox)

class ChooseMethod(QWidget):
    def __init__(self, parent):
        super(ChooseMethod, self).__init__(parent)
        self.setObjectName("Choose Method")
        
        self.resize(406, 422)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.type_activity = QtWidgets.QComboBox(self)
        self.type_activity.setMinimumWidth(120)
        self.type_activity.addItem("Aktywność")
        self.type_activity.addItem("Rehabilitacja")
        self.type_activity.setObjectName("type_activity")
        self.horizontalLayout.addWidget(self.type_activity)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.type_exercise = QtWidgets.QComboBox(self)
        self.type_exercise.setMinimumWidth(120)
        self.type_exercise.setEnabled(False)
        self.type_exercise.setObjectName("type_exercise")
        self.horizontalLayout_2.addWidget(self.type_exercise)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.type_physique = QtWidgets.QComboBox(self)
        self.type_physique.setMinimumWidth(120)
        self.type_physique.addItem("Atletyczna")
        self.type_physique.addItem("Normalna")
        self.type_physique.addItem("Otyła")
        self.type_physique.setObjectName("type_physique")
        self.horizontalLayout_3.addWidget(self.type_physique)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.humidity = QtWidgets.QLineEdit(self)
        self.humidity.setValidator(QIntValidator(0,100))

        self.humidity.setPlaceholderText("")
        self.humidity.setObjectName("humidity")
        self.horizontalLayout_4.addWidget(self.humidity)
        self.label = QtWidgets.QLabel(self)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.back = QtWidgets.QPushButton(self)
        self.back.setObjectName("back")
        self.horizontalLayout_5.addWidget(self.back)
        self.next = QtWidgets.QPushButton(self)
        self.next.setObjectName("next")
        self.horizontalLayout_5.addWidget(self.next)
        self.next.setEnabled(False)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.scrollArea = QtWidgets.QScrollArea(self)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 386, 250))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi()
        self.addActionButtons()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Wilgotnośc powietrza %"))
        self.next.setText(_translate("Form", "Dalej"))
        self.back.setText(_translate("Form", "Wróć"))

    def showScreen(self):
        if not self.humidity.text().__eq__(""):

            self.parent().setActivityExperience(self.type_activity.currentText(), self.type_exercise.currentText(), self.type_physique.currentText(),  self.humidity.text())

            self.parent().addScreen(self.getWidget())
            print(self.parent().user_login.get_advanced())
            if not self.parent().user_login.get_advanced():
                self.parent().chooseLotsMusclesAdvancedShow()
            else:
                self.parent().chooseLotsMusclesShow()
                
        else:
            self.createMessageBox("Wprowadz wilgotność")

    def addActionButtons(self):
        self.next.clicked.connect(lambda: self.showScreen())
        self.type_activity.view().pressed.connect(self.selectItemActivity)
        self.back.clicked.connect(lambda: self.backScreen())
        
    
    def selectItemActivity(self, index):
        self.type_exercise.setEnabled(True)
        self.next.setEnabled(True)
        item = self.type_activity.model().itemFromIndex(index)
        self.type_exercise.clear()
        if str(item.text()).__eq__("Aktywność"):
            self.type_exercise.addItem("Statyczna")
            self.type_exercise.addItem("Dynamiczna")
        elif str(item.text()).__eq__("Rehabilitacja"):
            self.type_exercise.addItem("Ćw. bierne")
            self.type_exercise.addItem("Ćw. czynne")
            self.type_exercise.addItem("Pacjent leżący")


    def backScreen(self):
        self.parent().openLastWidget()

    def getWidget(self):
        return str(self.objectName())

    def createMessageBox(self, message: str):
        msg = QMessageBox()
        msg.setWindowTitle("Błąd")
        msg.setText(message)
        msg.exec()