# Form implementation generated from reading ui file '.\dupa_medialna.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import   QUrl
from PyQt6.QtGui import QGuiApplication

from PyQt6.QtMultimedia import QAudioOutput, QMediaPlayer
from PyQt6.QtMultimediaWidgets import QVideoWidget


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        filename = "test.avi"
        self.mediaPlayer  = QMediaPlayer()
        self.mediaPlayer.setSource(QUrl.fromLocalFile(filename))
        self.videoWidget = QVideoWidget()

        self.verticalLayout.addWidget(self.videoWidget)
        self.playButton = QtWidgets.QPushButton(Form)
        self.playButton.setObjectName("pushButton")
        self.playButton.clicked.connect(lambda:self.play())
        self.verticalLayout.addWidget(self.playButton)


        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 380, 250))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)

        self.mediaPlayer.setVideoOutput(self.videoWidget)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def play(self):
        print("dupa")
        self.mediaPlayer.play()


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.playButton.setText(_translate("Form", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
