# Form implementation generated from reading ui file '.\ui_file\managment_sensor_widget.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import (QWidget,QMessageBox, QHBoxLayout)
import ipaddress

class ConnectionSensor(QHBoxLayout):
    def __init__(self, parent,**kwargs):
        super(ConnectionSensor, self).__init__(parent)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.addItem(spacerItem)
        self.label = QtWidgets.QLabel()
        self.label.setObjectName("label")
        self.addWidget(self.label)
        self.humidity = QtWidgets.QLineEdit()
        self.humidity.setPlaceholderText("")
        self.humidity.setObjectName("humidity_2")
        self.addWidget(self.humidity)
        self.connect = QtWidgets.QPushButton()
        self.connect.setObjectName("connect")
        self.addWidget(self.connect)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.addItem(spacerItem1)
        self.number = kwargs.get("number", 1)
        self.retranslateUi()
        self.addActionBattons()
    
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("ManagmentSensor", "Wprowadz adres taśmy: "+'{:02d}'.format(self.number)))
        self.connect.setText(_translate("ManagmentSensor", "Połącz"))

    def addActionBattons(self):
        self.connect.clicked.connect(lambda: self.connectSensor())

    def connectSensor(self):
        
        objectName: str = str(self.sender().objectName())
        try:
            if objectName.__eq__("connect_1"):
                ipaddress.IPv4Address(str(self.humidity_2.text()))
                self.parent().addIpAddressManageSensor=self.humidity_2.text()
                
            elif objectName.__eq__("connect_2"):
                ipaddress.IPv4Address(str(self.humidity_3.text()))
                self.parent().addIpAddressManageSensor=self.humidity_3.text()
            self.createMessageBox("Nie udało się połączyć")
                
        except ipaddress.AddressValueError:
            self.createMessageBox("Połączenie nie nastąpiło, podałeś nieprawidłowy addres ip")

        

    def createMessageBox(self, message: str):
        msg = QMessageBox()
        msg.setWindowTitle("Błąd")
        msg.setText(message)
        msg.exec()

class ManagmentSensor(QWidget):
    def __init__(self, parent):
        super(ManagmentSensor, self).__init__(parent)
        self.lot_of_muscles: int = self.parent().getQuantityMangeSensor()
        self.setObjectName("Managment Sensor")
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")

        for i in range(self.lot_of_muscles):
            self.verticalLayout.addLayout(ConnectionSensor(self, number = i+1))


        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.back = QtWidgets.QPushButton(self)
        self.back.setObjectName("back")
        self.horizontalLayout_5.addWidget(self.back)
        self.next = QtWidgets.QPushButton(self)
        self.next.setObjectName("next")
        self.horizontalLayout_5.addWidget(self.next)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.scrollArea = QtWidgets.QScrollArea(self)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 380, 184))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi()
        self.addActionBattons()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("ManagmentSensor", "Form"))
       
        self.back.setText(_translate("ManagmentSensor", "Wróć"))
        self.next.setText(_translate("ManagmentSensor", "Rozpocznij"))


    def addActionBattons(self):
        self.next.clicked.connect(lambda: self.showScreen())
        self.back.clicked.connect(lambda: self.backScreen())  
    
    def backScreen(self):
        self.parent().openLastWidget()

    def showScreen(self):
        self.parent().addScreen(self.getWidget())
        self.parent().startReferenceShow()

    def createMessageBox(self, message: str):
        msg = QMessageBox()
        msg.setWindowTitle("Błąd")
        msg.setText(message)
        msg.exec()
    
    def getWidget(self):
        return str(self.objectName())